version: '3'
services:
  dev:
    container_name: 'announcing-dev'
    stdin_open: true
    tty: true
    ports:
      - '127.0.0.1:5173:5173'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/announcing/app:delegated
      - pnpm-store-cache:/pnpm-store-cache
    working_dir: /announcing/app
    command: sh -c './docker-init.sh && bash'
volumes:
  pnpm-store-cache:
