/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `Announcing`'s JSON-Schema
 * via the `definition` "Date".
 */
export type Date = string;

export interface Announcing {}
/**
 * This interface was referenced by `Announcing`'s JSON-Schema
 * via the `definition` "Post".
 */
export interface Post {
  title: string;
}
/**
 * This interface was referenced by `Announcing`'s JSON-Schema
 * via the `definition` "Announcement".
 */
export interface Announcement {
  updated: Date;
  info: {
    name: string;
  };
  posts?: Post[];
  refs?: unknown[];
}
