FROM node:18.17.1-slim

# Install basic development tools
RUN apt update && apt install -y less man-db sudo git

# Ensure default `node` user has access to `sudo`
ARG USERNAME=node
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME

# Set `DEVCONTAINER` environment variable to help with orientation
ENV DEVCONTAINER=true

RUN npm install -g pnpm@8

RUN echo 'export PS1="\W \$ "' >> /root/.bashrc
